version: '3'

services:
  # Database
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - '3369:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: check_now
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    networks:
      - custom
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - custom

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    networks:
      - custom

networks:
  custom:
volumes:
  db_data:
  cache:
